I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/level_1.rpy", line 1458, in script
    p2 "Hey Cathy, I checked out CORE today but I could find any valid information[about]. I just found this photograph in the trash. Maybe we should give up and move on.."
KeyError: 'about'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/level_1.rpy", line 1458, in script
    p2 "Hey Cathy, I checked out CORE today but I could find any valid information[about]. I just found this photograph in the trash. Maybe we should give up and move on.."
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\character.py", line 1337, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\character.py", line 1251, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\character.py", line 1231, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\substitutions.py", line 278, in substitute
    s = formatter.vformat(s, (), kwargs) # type: ignore
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 165, in vformat
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 205, in _vformat
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\substitutions.py", line 168, in get_field
    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 270, in get_field
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 227, in get_value
KeyError: 'about'

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Social Engineering Game 1.0
Fri Jan 26 13:21:55 2024
