I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/level_1.rpy", line 1023, in script
    menu:
  File "game/level_1.rpy", line 1024, in <module>
    "Investigate Support Staff Contacts" if support_staff_contacts_done:
NameError: name 'support_staff_contacts_done' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/level_1.rpy", line 1023, in script
    menu:
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1922, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\exports.py", line 1072, in menu
    condition = renpy.python.py_eval(condition)
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/level_1.rpy", line 1024, in <module>
    "Investigate Support Staff Contacts" if support_staff_contacts_done:
NameError: name 'support_staff_contacts_done' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Social Engineering Game 1.0
Sun Feb 25 19:14:50 2024
