I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/level_3.rpy", line 183, in script
    define mercenary1_info = InventoryData("Jack Morrison")
  File "game/level_3.rpy", line 183, in <module>
    define mercenary1_info = InventoryData("Jack Morrison")
TypeError: __init__() missing 1 required positional argument: 'description'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/level_3.rpy", line 183, in script
    define mercenary1_info = InventoryData("Jack Morrison")
  File "C:\Users\Deep\OneDrive\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 2508, in execute
    self.set()
  File "C:\Users\Deep\OneDrive\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 2522, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\Deep\OneDrive\Desktop\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/level_3.rpy", line 183, in <module>
    define mercenary1_info = InventoryData("Jack Morrison")
TypeError: __init__() missing 1 required positional argument: 'description'

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Social Engineering Game 1.0
Sat May  4 21:19:54 2024
